### ISSUE TITLE
导致游戏闪退

### ISSUE THREAD

**Issue by dalaoshus** [Megghy/MultiSEngine#10]
大概率在进入服务器时候会导致游戏闪退[不给设置默认服务器也一样]

使用游戏版本 PE 1.4.3.2
![Screenshot_2022-05-10-21-57-43-879_com microsoft rdc androie](https://user-images.githubusercontent.com/79201070/167647069-12a18e07-0230-4f0e-91a9-e86a108b7918.jpg)

**Comment by Megghy** [comment]
闪退的话找不到原因所以没法解决

**Comment by dalaoshus** [comment]
> 

32位的一进就闪退64位就很少闪退，不知对修复有没有帮助。

**Comment by Megghy** [comment]
大概没有
如果能拿到错误日志之类的东西倒有点用
我的评价是不如等pcpe版本同步

**Comment by dalaoshus** [comment]
> 大概没有 如果能拿到错误日志之类的东西倒有点用 我的评价是不如等pcpe版本同步

10:55:41 - [Log] [reply] disconnected. 
10:56:00 - [Log] 103.57.12.57:7096 trying to connect...
10:56:00 - [Info] Version of 103.57.12.57:7096 is v1.4.3.2<244>.
10:56:01 - [Error] An error occurred while processing packet TrProtocol.Packets.SpawnPlayer.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MultiSEngine.Modules.Data.<>c.<get_Motd>b__8_0(ClientData c)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at MultiSEngine.Modules.Data.get_Motd()
   at MultiSEngine.Core.Adapter.FakeWorldAdapter.GetPacket(Packet packet)
   at MultiSEngine.Core.Adapter.BaseAdapter.ProcessPacketLoop()
10:56:02 - [Log] [reply] disconnected. 

日志报错
客户端是1.4.3.6

**Comment by Megghy** [comment]
程序目录截个图

**Comment by dalaoshus** [comment]
> 程序目录截个图

![Uploading Screenshot_2022-05-28-11-27-23-461_com.microsoft.rdc.androie.jpg…]()

**Comment by dalaoshus** [comment]
> 程序目录截个图

![Screenshot_2022-05-28-11-27-23-461_com microsoft rdc androie](https://user-images.githubusercontent.com/79201070/170808150-0104a56d-666c-4922-b084-c08ce2c477d9.jpg)

**Comment by Megghy** [comment]
把motd删了重开看看

**Comment by josefcorosado** [comment]
Hello.
I'm having LegacyMultiplayer4 error and cannot log in with mobile.

**Comment by Megghy** [comment]
You can test it with this command in the console: test (Server name) -detail
Also this project doesn't have much compatibility with pe and may have a lot of problems
