### ISSUE TITLE
无法与世界交互

### ISSUE THREAD

**Issue by LingEmberMaple** [Megghy/MultiSEngine#11]
通过MultiSEngine连接到服务器后，挖掘无法产生掉落物，重新连接后，之前已挖掘的方块复原

**Comment by Megghy** [comment]
有没有报错

**Comment by LingEmberMaple** [comment]
> 有没有报错

没有报错，兼容插件已经安装了

**Comment by Megghy** [comment]
1436我没复现出来这毛病, 没有报错的话我也不清楚是哪块的问题

**Comment by LingEmberMaple** [comment]
> 1436我没复现出来这毛病, 没有报错的话我也不清楚是哪块的问题

如果服务器设置了密码，则100%触发这个bug

我将测试环境打包上传，[下载连接](https://we.tl/t-4Mhp25qzjt)(文件过大)

**Comment by LingEmberMaple** [comment]
> > 1436我没复现出来这毛病, 没有报错的话我也不清楚是哪块的问题
> 
> 如果服务器设置了密码，则100%触发这个bug
> 
> 我将测试环境打包上传，[下载连接](https://we.tl/t-4Mhp25qzjt)(文件过大)

里面包括了俩次测试的log(不带密码、带密码)

**Comment by Megghy** [comment]
tr网络代码太屎了 翻了半天都没找到是哪的问题, 估计是state方面的毛病, 只能建议先别带密码
