### ISSUE TITLE
Update for Terraria 1.4.4

### ISSUE THREAD

**Issue by dark22** [Megghy/MultiSEngine#13]
Are there any future plans to update this repository and its TrProtocol dependency to the new Terraria version? I'm not pressing about it, but as the activity has been little, I decided to ask. Thanks for the project!

**Comment by Megghy** [comment]
I've been busy with some things lately, and it will probably be a while before I can update

**Comment by dark22** [comment]
No problems! Glad to hear it will be updated. I'll keep an eye out here as I'm trying to update, but this is not within my knowledge of Terraria's network packets. Thank you for your attention.

**Comment by dark22** [comment]
I don't want to bother about news, but as it's been a while, an update, even a basic one that makes it work, would be possible, I tried to do something, but it's far from my knowledge about packages and the game crashes when entering, even updating some packages such as loadout. Please don't abandon this project, it's one of the few proxy alternatives we have in the community. If you can't keep it, could you recommend someone who can? Thank you for your time invested in this.

**Comment by Megghy** [comment]
It should be in the near future

**Comment by dark22** [comment]
Thank you very much for the reply, I will look forward to the return of this project. I'm really happy to hear that you plan to update!

**Comment by Megghy** [comment]
I think I've finished the general update, maybe you can test the following files first to see if they work. Looking forward to your feedback!
The new version requires [.Net 7](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)


[MultiSEngine.zip](https://github.com/Megghy/MultiSEngine/files/10403846/MultiSEngine.zip)

**Comment by dark22** [comment]
Hi! Sorry for the delay in getting back to you, my work took up all my time this week. I did some tests with the PC version with some servers on the local machine and I didn't find any errors, it works fine. But as it was just a test without debugging, I may have missed something. I'll wait for the update of the repository and the plugin for TShock with the source code to do more specific tests. Thank you immensely for your work on this and for answering my messages.

**Comment by Megghy** [comment]
Changes have been pushed
