### ISSUE TITLE
File 

### ISSUE THREAD

**Issue by imnagarajan** [Megghy/MultiSEngine#14]
![Screenshot_20230109-233641](https://user-images.githubusercontent.com/107058543/211377093-d8924104-7c91-488c-ab38-196cef1d514b.png)
WhatWhat is this file for ?
And please update this for terraria 1.4.4

**Comment by imnagarajan** [comment]
And i can't remove ones i remove the file and i restart it's comes again

**Comment by imnagarajan** [comment]
@Megghy

**Comment by Megghy** [comment]
I'm not sure where those plugins come from, this project doesn't interact directly with tshock. 
It will probably take a while to update, I've been busy with other things lately

**Comment by imnagarajan** [comment]
It's ok take your timr

**Comment by imnagarajan** [comment]
> It's ok take your timr

When i get the plugin?

**Comment by Megghy** [comment]
Updates have been released
