### ISSUE TITLE
MSE v1.1.0.1 - Broken blocks not appearing or dropping

### ISSUE THREAD

**Issue by GlyphBee** [Megghy/MultiSEngine#15]
Hello.

When joining servers connected by MultiSEngine, broken blocks do not appear or drop. For example: a tree is mined, it breaks, but no wood drops.

Using:
- Ubuntu
- Clean install and default settings for TShock and MultiSEngine
- MultiSEngine v1.1.0.1
- TShock v5.1.3 for Terraria v1.4.4.9

If more information is needed please let me know what I can provide.

Thank you.

**Comment by Megghy** [comment]
I seem to have fixed this issue in 1.1.0.1, are you sure you're using the latest version? Or are there any errors in the console

**Comment by GlyphBee** [comment]
I tested again with all new installs and this is only happening is `DisableLoginBeforeJoin` is set to `false` in the TShock config.json. I've set `DisableLoginBeforeJoin` to `true` and it is now working.

Thank you for your quick reply.

**Comment by Megghy** [comment]
fixed
