### ISSUE TITLE
I have issues in the release 

### ISSUE THREAD

**Issue by imnagarajan** [Megghy/MultiSEngine#16]
There is no .dll or any another file it's empty

**Comment by imnagarajan** [comment]
@Megghy

**Comment by Megghy** [comment]
I checked it and there is no problem

**Comment by imnagarajan** [comment]
![Screenshot_20230122-121653](https://user-images.githubusercontent.com/107058543/213904188-19cee8c3-d1da-493e-bf80-5141945774b2.png)
See?

**Comment by Megghy** [comment]
![Screenshot_2023-01-22-14-38-29-275_ru zdevs zarchiver pro](https://user-images.githubusercontent.com/44969916/213904240-842c1420-7014-4380-bba8-d5f35dfa590a.jpg)

**Comment by imnagarajan** [comment]
Mm i forgot to download that app

**Comment by imnagarajan** [comment]
Can I connect two server in one server like freebuild to survival

**Comment by Megghy** [comment]
yup

**Comment by imnagarajan** [comment]
Ok but there is no .json file

**Comment by imnagarajan** [comment]
![Uploading Screenshot_20230122-122741.png…]()

**Comment by Megghy** [comment]
Run once

**Comment by imnagarajan** [comment]
![Screenshot_20230122-122741](https://user-images.githubusercontent.com/107058543/213904586-06126e3e-1fd3-4397-ae8b-dd5f2cf295d5.png)
What is this!

**Comment by Megghy** [comment]
Have you installed .net7 yet?

**Comment by imnagarajan** [comment]
Iam using mobile is it work in mobile

**Comment by Megghy** [comment]
This has nothing to do with whether it runs on mobile or not, no matter where it runs you need to install .net7, which is the running environment for this program

**Comment by imnagarajan** [comment]
How do I install .net7

**Comment by Megghy** [comment]
Google.com

**Comment by imnagarajan** [comment]
I searched nothing it's all works in pc not in mobile

**Comment by Megghy** [comment]
For mobiles, that's .net7 for arm64, and yours seems to be a web panel

**Comment by imnagarajan** [comment]
Can you teach me how to update a plugin on mobile

**Comment by imnagarajan** [comment]
@Megghy

**Comment by imnagarajan** [comment]
Please

**Comment by imnagarajan** [comment]
Is there any easy way to use the plugin @Megghy

**Comment by Megghy** [comment]
If you are using an environment that can run tshock, then you should be able to run this version, otherwise if you don't know how to configure your environment, then this project is not for you.
[MultiSEngine.zip](https://github.com/Megghy/MultiSEngine/files/10474445/MultiSEngine.zip)

**Comment by imnagarajan** [comment]
Ok let's try

**Comment by imnagarajan** [comment]
Do i want to put all .dll file into server plugin folder

**Comment by Megghy** [comment]
This is not a tshock plugin, you don't need it and can't put it in the plugins directory, it's a separate program, and obviously you need to unpack all the files together

**Comment by imnagarajan** [comment]
Ok it's working now how to setup ?

**Comment by imnagarajan** [comment]
> This is not a tshock plugin, you don't need it and can't put it in the plugins directory, it's a separate program, and obviously you need to unpack all the files together

I just do is i unziped and put all .dll file into server plugin folder

**Comment by imnagarajan** [comment]
And it's now no error

**Comment by imnagarajan** [comment]
Now how to setup i mean how i connect two server

**Comment by Megghy** [comment]
Well, theoretically this can't be placed in the plugins folder
Open the two servers you want to use, change the parameters to your server according to the existing examples in the configuration file, for details see https://www.yuque.com/megghy/multisengine/zw5my1 , use the translation tool

**Comment by imnagarajan** [comment]
Wait i have to open .exe file

**Comment by imnagarajan** [comment]
But i am using mobile

**Comment by imnagarajan** [comment]
@Megghy

**Comment by sgkoishi** [comment]
Ask your skynode.pro provider.
