### ISSUE TITLE
进不了带密码的服务器

### ISSUE THREAD

**Issue by ABinUp** [Megghy/MultiSEngine#2]
问题出现场景：
TShock设置"DisableUUIDLogin": true。
新建人物直连MultiSEngine，则会一直提示无法连接。
MultiSEngine控制台一直抛错：
[Info] Switching [123] to the server: [game1]
[Log] Update the index of [123]: 1 => 2.
[Error] An error occurred while processing packet TrProtocol.Packets.RequestPassword.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MultiSEngine.Core.Adapter.VisualPlayerAdapter.GetPacket(Packet& packet)
   at MultiSEngine.Core.Adapter.AdapterBase.ProcessPacketLoop()
[Warn] Cannot continue to maintain connection between 123 and server
System.IO.IOException: Unable to read data from the transport connection: 你的主机中的软件中止了一个已建立的连接。.
 ---> System.Net.Sockets.SocketException (10053): 你的主机中的软件中止了一个已建立的连接。
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt16()
   at TrProtocol.PacketSerializer.Deserialize(BinaryReader br0)
   at MultiSEngine.Core.Adapter.AdapterBase.RecieveLoop()

**Comment by Megghy** [comment]
[MultiSEngine.zip](https://github.com/Megghy/MultiSEngine/files/7496490/MultiSEngine.zip)
试下这个

**Comment by ABinUp** [comment]
TShock配置文件Config.json设置"DisableUUIDLogin": true
TShock配置文件sscconfig.json设置"Enabled": true
MultiSEngine配置文件Config.json设置"SwitchToDefaultServerOnJoin": false
新建人物，新名称，直连MultiSEngine，再进行传服操作。
-------------------
问题如下：
1，貌似无法正常游戏，例如采集
2，无法传服

**Comment by Megghy** [comment]
报错内容

**Comment by ABinUp** [comment]
控制台没有报错，游戏中提示  正在跳转中, 请勿使用此命令

**Comment by Megghy** [comment]
我本地测试没发现问题 你是不是没把文件替换全

**Comment by ABinUp** [comment]
用的上面链接的文件。
你测试的时候是使用了我列举的设置吗？我这边问题依然在。
3种可能。
1，你给我的链接文件和你测试用的程序不一致
2，你未使用我列举的设置
3，我有问题

**Comment by ABinUp** [comment]
[Warn] Cannot continue to maintain connection between abc and server game1
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt16()
   at TrProtocol.PacketSerializer.Deserialize(BinaryReader br0)
   at MultiSEngine.Core.Adapter.AdapterBase.RecieveLoop()
[Warn] Unallowed transmission requests for [abc]

**Comment by Megghy** [comment]
服务端和客户端是什么版本

**Comment by ABinUp** [comment]
服务端：TShock4.5.5_Terraria_1.4.2.3
客户端：steam - Terraria_1.4.2.3

**Comment by Megghy** [comment]
[MultiSEngine.zip](https://github.com/Megghy/MultiSEngine/files/7505409/MultiSEngine.zip)

**Comment by ABinUp** [comment]
能正常进服了，也能在两个世界互相传送了。
但是依然不能在任意一个世界正常游戏，例如，采集木头或者击杀怪物。
游戏时MultiSEngine控制台无异常显示。
泰拉瑞亚服务器控制台一直滚动日志
[MultiSEngine] modified tile square for [bcd].
[MultiSEngine] modified tile square for [bcd].
[MultiSEngine] modified tile square for [bcd].
[MultiSEngine] modified tile square for [bcd].
[MultiSEngine] modified tile square for [bcd].
[MultiSEngine] modified tile square for [bcd].
[MultiSEngine] modified tile square for [bcd].
[MultiSEngine] modified tile square for [bcd].
。
上述为人物bcd在世界进行伐木即击杀怪物操作，采集不了木头，且怪物无法被杀死。

**Comment by Megghy** [comment]
把ts那的插件删了也一样?

**Comment by ABinUp** [comment]
对

**Comment by Megghy** [comment]
无法复现

**Comment by ABinUp** [comment]
你服务器怎么设置密码的，是不是跟我一样在双击泰拉瑞亚开服程序后，再一个一个设置的

**Comment by Megghy** [comment]
是

**Comment by ABinUp** [comment]
MultiSEngine-test
120.26.178.185:12777
.
server1
120.26.178.185:12778  
密码123
.
server2
120.26.178.185:12779
密码123

**Comment by ABinUp** [comment]
MultiSEngine配置文件
http://120.26.178.185:12776/MultiSEngine/Config.json
.
server1配置文件
http://120.26.178.185:12776/server1/tshock/config.json
http://120.26.178.185:12776/server1/tshock/sscconfig.json
.
server2配置文件
http://120.26.178.185:12776/server2/tshock/config.json
http://120.26.178.185:12776/server2/tshock/sscconfig.json

**Comment by Megghy** [comment]
装没装什么插件

**Comment by ABinUp** [comment]
没
